---

- name: Install packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ sshd_packages }}'

- name: Copy configuration file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart sshd

- name: Validate configuration file is healthy
  command: /usr/sbin/sshd -t
  changed_when: false

- name: Add port to SELinux ssh_port_t
  seport:
    ports: '{{ sshd_port }}'
    proto: tcp
    setype: ssh_port_t
    state: present

- name: Enable and start sshd service
  service:
    name: sshd
    enabled: yes
    state: started
